language: php

dist: trusty
sudo: false

php: 7.4

env:
  - COMPOSER_MEMORY_LIMIT=-1

install:
  - travis_retry composer update
  - cd dev-tools; travis_retry composer update; cd ..

before_script:
  - composer show

script:
  - ./dev-tools/vendor/bin/php-cs-fixer --diff --dry-run -v --allow-risky=yes fix
  - ./dev-tools/vendor/bin/php-cs-fixer --diff --dry-run -v --allow-risky=yes fix .php_cs.dist
  - vendor/bin/phpunit

after_script:
  - travis_retry bin/coveralls.sh
